### PR TITLE
[C4A-527] Increase address widths for small screen sizes on Business …

### PR DESCRIPTION
**Pull request by RossWebsterWork**
[C4A-527] Increase address widths for small screen sizes on Business Details

### CODE REVIEW

**Comment by DanielTurner** [comment]
@RossWebsterWork just update your branch with the latest develop branch code.

**Comment by duttonw** [comment]
@RossWebsterWork  i've just rebased your work on develop and forced pushed for you. your change is simple enough it should pass.

@DanielTurner  should i also update kyfb package like i did for this repo?

**Review by duttonw — APPROVED** [review]

**Review by DanielTurner — APPROVED** [review]

**Comment by DanielTurner** [comment]
@duttonw probably because the versions in the lock are probably outdated compared to the ones we are developing with.

**Comment by duttonw** [comment]
@DanielTurner  I just included the lock file, we never had it included before.

**Pull request merged**
